/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2_proyecto8_fredysalvador;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fredy Salvador
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        Usuario usuario1 = new Usuario("enuila", "wynaut1325", 20);
        usuarios.add(usuario1);
    }

    private void abrir_ingresar() {
        jd_Ingresar.pack();
        jd_Ingresar.setLocationRelativeTo(this);
        jd_Ingresar.setModal(true);
        jd_Ingresar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Ingresar = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jd_AgregarSolista = new javax.swing.JDialog();
        btAgregarArtista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnomuser = new javax.swing.JTextField();
        tcontrasenaartista = new javax.swing.JTextField();
        tnomartistico = new javax.swing.JTextField();
        tedadartista = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tgenmusical1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jd_AgregarBanda = new javax.swing.JDialog();
        tnomuser2 = new javax.swing.JTextField();
        tcontrasena2 = new javax.swing.JTextField();
        tedadcliente = new javax.swing.JTextField();
        btAgregarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tnumerointegrante1 = new javax.swing.JTextField();
        tgenmusical2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tnomBanda1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jd_Login = new javax.swing.JDialog();
        tcont = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btIngresar = new javax.swing.JButton();
        tusuar = new javax.swing.JTextField();
        jd_listaaruser = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsers = new javax.swing.JTable();
        bteliminarusuario = new javax.swing.JButton();
        jd_AgregarEvento = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ciudad2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lugar2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        capacidad2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jd_Simulacion = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        verusuario = new javax.swing.JButton();
        agregarusuarioscliente = new javax.swing.JButton();
        agregarusuariosartistas = new javax.swing.JButton();
        eventoing = new javax.swing.JButton();
        Gen_Simulacion = new javax.swing.JButton();
        salirusuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jButton5.setText("Registrar Solistas");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Login Usuario");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Menu de Inicio");

        jButton7.setText("Registrar Bandas");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_IngresarLayout = new javax.swing.GroupLayout(jd_Ingresar.getContentPane());
        jd_Ingresar.getContentPane().setLayout(jd_IngresarLayout);
        jd_IngresarLayout.setHorizontalGroup(
            jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_IngresarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jd_IngresarLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_IngresarLayout.setVerticalGroup(
            jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_IngresarLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        btAgregarArtista.setText("Agregar");
        btAgregarArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarArtistaMouseClicked(evt);
            }
        });
        btAgregarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarArtistaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de Usuario:");

        jLabel3.setText("Contraseña de Usuario:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Nombre Solista:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Agregar Solista");

        jLabel15.setText("Genero Musical:");

        javax.swing.GroupLayout jd_AgregarSolistaLayout = new javax.swing.GroupLayout(jd_AgregarSolista.getContentPane());
        jd_AgregarSolista.getContentPane().setLayout(jd_AgregarSolistaLayout);
        jd_AgregarSolistaLayout.setHorizontalGroup(
            jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tnomuser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tedadartista, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tnomartistico, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tcontrasenaartista, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tgenmusical1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btAgregarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jd_AgregarSolistaLayout.setVerticalGroup(
            jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarSolistaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnomuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tcontrasenaartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tedadartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tnomartistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tgenmusical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAgregarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btAgregarCliente.setText("Agregar");
        btAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarClienteMouseClicked(evt);
            }
        });

        jLabel7.setText("Nombre de Usuario:");

        jLabel8.setText("Contraseña de Usuario:");

        jLabel9.setText("Edad:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Agregar Banda");

        jLabel17.setText("Numero Integrantes:");

        jLabel19.setText("Genero Musical:");

        jLabel20.setText("Nombre Banda:");

        javax.swing.GroupLayout jd_AgregarBandaLayout = new javax.swing.GroupLayout(jd_AgregarBanda.getContentPane());
        jd_AgregarBanda.getContentPane().setLayout(jd_AgregarBandaLayout);
        jd_AgregarBandaLayout.setHorizontalGroup(
            jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tnomuser2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tedadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(tcontrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tnumerointegrante1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tgenmusical2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tnomBanda1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jd_AgregarBandaLayout.setVerticalGroup(
            jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tnomuser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tcontrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tedadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tgenmusical2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tnomBanda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tnumerointegrante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel6.setText("jLabel6");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setText("Ingresar al Sistema");

        jLabel13.setText("Usuario:");

        jLabel14.setText("Contraseña:");

        btIngresar.setText("Ingresar");
        btIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIngresarMouseClicked(evt);
            }
        });
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        btIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btIngresarKeyPressed(evt);
            }
        });

        tusuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tusuarMouseClicked(evt);
            }
        });
        tusuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_LoginLayout = new javax.swing.GroupLayout(jd_Login.getContentPane());
        jd_Login.getContentPane().setLayout(jd_LoginLayout);
        jd_LoginLayout.setHorizontalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12))
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_LoginLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(11, 11, 11)))
                        .addGap(38, 38, 38)
                        .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tcont, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(tusuar)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jd_LoginLayout.setVerticalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(31, 31, 31)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tusuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        TablaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Usuario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsers);

        bteliminarusuario.setText("Eliminar");
        bteliminarusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bteliminarusuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listaaruserLayout = new javax.swing.GroupLayout(jd_listaaruser.getContentPane());
        jd_listaaruser.getContentPane().setLayout(jd_listaaruserLayout);
        jd_listaaruserLayout.setHorizontalGroup(
            jd_listaaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaaruserLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addGroup(jd_listaaruserLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bteliminarusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_listaaruserLayout.setVerticalGroup(
            jd_listaaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaaruserLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bteliminarusuario)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setText("Agregar Evento");

        jLabel18.setText("Fecha:");

        jLabel21.setText("Ciudad:");

        jLabel22.setText("Lugar:");

        jLabel23.setText("Capacidad:");

        jButton2.setText("Agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AgregarEventoLayout = new javax.swing.GroupLayout(jd_AgregarEvento.getContentPane());
        jd_AgregarEvento.getContentPane().setLayout(jd_AgregarEventoLayout);
        jd_AgregarEventoLayout.setHorizontalGroup(
            jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ciudad2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lugar2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jd_AgregarEventoLayout.setVerticalGroup(
            jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lugar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jd_SimulacionLayout = new javax.swing.GroupLayout(jd_Simulacion.getContentPane());
        jd_Simulacion.getContentPane().setLayout(jd_SimulacionLayout);
        jd_SimulacionLayout.setHorizontalGroup(
            jd_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_SimulacionLayout.setVerticalGroup(
            jd_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jToolBar1.setRollover(true);

        jButton1.setText("Ingresar al Sistema");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton1);

        verusuario.setText("Ver Usuario + Eliminar");
        verusuario.setEnabled(false);
        verusuario.setFocusable(false);
        verusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verusuarioMouseClicked(evt);
            }
        });
        verusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verusuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(verusuario);

        agregarusuarioscliente.setText("Agregar Solista");
        agregarusuarioscliente.setEnabled(false);
        agregarusuarioscliente.setFocusable(false);
        agregarusuarioscliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarusuarioscliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarusuarioscliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarusuariosclienteMouseClicked(evt);
            }
        });
        jToolBar1.add(agregarusuarioscliente);

        agregarusuariosartistas.setText("Agregar Banda");
        agregarusuariosartistas.setEnabled(false);
        agregarusuariosartistas.setFocusable(false);
        agregarusuariosartistas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarusuariosartistas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarusuariosartistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarusuariosartistasMouseClicked(evt);
            }
        });
        jToolBar1.add(agregarusuariosartistas);

        eventoing.setText("Agregar Evento");
        eventoing.setEnabled(false);
        eventoing.setFocusable(false);
        eventoing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eventoing.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eventoing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventoingMouseClicked(evt);
            }
        });
        jToolBar1.add(eventoing);

        Gen_Simulacion.setText("Generar Simulacion");
        Gen_Simulacion.setEnabled(false);
        Gen_Simulacion.setFocusable(false);
        Gen_Simulacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Gen_Simulacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Gen_Simulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Gen_SimulacionMouseClicked(evt);
            }
        });
        jToolBar1.add(Gen_Simulacion);

        salirusuario.setText("Cerrar Sesion");
        salirusuario.setEnabled(false);
        salirusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salirusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirusuarioMouseClicked(evt);
            }
        });
        jToolBar1.add(salirusuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 271, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        abrir_ingresar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jd_AgregarSolista.pack();
        jd_AgregarSolista.setLocationRelativeTo(this);
        jd_AgregarSolista.setModal(true);
        jd_AgregarSolista.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jd_AgregarBanda.pack();
        jd_AgregarBanda.setLocationRelativeTo(this);
        jd_AgregarBanda.setModal(true);
        jd_AgregarBanda.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton5MouseClicked

    private void btAgregarArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarArtistaMouseClicked
        // TODO add your handling code here:
        String nombre, contrasena, nom_art, gen_musc;
        int edad;
        try {
            nombre = tnomuser.getText();
            contrasena = tcontrasenaartista.getText();
            nom_art = tnomartistico.getText();
            gen_musc = tgenmusical1.getText();
            //  lis_musc = ListaMusical1.getText();
            //  List<String> listaMusical = Arrays.asList(lis_musc.split(","));
            edad = Integer.parseInt(tedadartista.getText());

            Solistas s = new Solistas(nom_art, gen_musc, nombre, contrasena, edad);

            usuarios.add(s);

            String op = "s";
            int cant = 1;
            while (op.equals("s")) {
                s.getCancion().add(
                        new Cancion(
                                JOptionPane.showInputDialog("Nombre de la Cancion"),
                                Double.parseDouble(JOptionPane.showInputDialog("Tiempo en Segundos")), nom_art)
                );
                cant++;
                op = JOptionPane.showInputDialog(
                        "Desea continuar s/n");
            }
            adminSolista ap = new adminSolista("./solista.cbm");
            ap.cargarArchivo();
            ap.setSolista(s);
            ap.escribirArchivo();

            JOptionPane.showMessageDialog(this,
                    "Valores Ingresado Correctamente");
            tnomuser.setText("");
            tcontrasenaartista.setText("");
            tedadartista.setText("");
            tnomartistico.setText("");
            tgenmusical1.setText("");

            jd_AgregarSolista.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Ocurrio un error y no se guardaron los datos");
        }

    }//GEN-LAST:event_btAgregarArtistaMouseClicked

    private void btAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarClienteMouseClicked
        // TODO add your handling code here:
        String nombre, contrasena, nom_art, gen_musc, lis_musc, banda;
        int edad, integrantes;
        try {
            nombre = tnomuser2.getText();
            contrasena = tcontrasena2.getText();
            gen_musc = tgenmusical2.getText();
            edad = Integer.parseInt(tedadcliente.getText());
            banda = tnomBanda1.getText();
            integrantes = Integer.parseInt(tnumerointegrante1.getText());

            Bandas s = new Bandas(banda, gen_musc, integrantes, nombre, contrasena, edad);

            usuarios.add(s);

            String op = "s";
            int cant = 1;
            while (op.equals("s")) {
                s.getCancion().add(
                        new Cancion(
                                JOptionPane.showInputDialog("Nombre de la Cancion"),
                                Double.parseDouble(JOptionPane.showInputDialog("Tiempo en Segundos")), banda)
                );
                cant++;
                op = JOptionPane.showInputDialog(
                        "Desea continuar s/n");
            }
            adminBanda ap = new adminBanda("./banda.cbm");
            ap.cargarArchivo();
            ap.setBanda(s);
            ap.escribirArchivo();

            JOptionPane.showMessageDialog(this,
                    "Valores Ingresado Correctamente");
            tnomuser2.setText("");
            tcontrasena2.setText("");
            tedadcliente.setText("");
            tgenmusical2.setText("");
            tnomBanda1.setText("");
            tnumerointegrante1.setText("");

            jd_AgregarBanda.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_btAgregarClienteMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        jd_Login.pack();
        jd_Login.setLocationRelativeTo(this);
        jd_Login.setModal(true);
        jd_Login.setVisible(true);

    }//GEN-LAST:event_jButton6MouseClicked

    private void btIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIngresarMouseClicked
        // TODO add your handling code here:
        boolean bandera = false;
        for (Usuario temp : usuarios) {
            if (temp.getUsername().equals(tusuar.getText())
                    && temp.getPassword().equals(tcont.getText())) {

                bandera = true;
                break;
            }
        }

        if (bandera) {
            tusuar.setText("");
            tcont.setText("");
            jButton1.setEnabled(false);
            verusuario.setEnabled(true);
            agregarusuarioscliente.setEnabled(true);
            agregarusuariosartistas.setEnabled(true);
            eventoing.setEnabled(true);
            Gen_Simulacion.setEnabled(true);
            salirusuario.setEnabled(true);

            jd_Login.setVisible(false);
            jd_Ingresar.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(jd_Ingresar, "Usuario Equivocado");
        }

    }//GEN-LAST:event_btIngresarMouseClicked

    private void btIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btIngresarKeyPressed

        if (tcont.getText().length() >= 0) {

            btIngresar.setEnabled(true);

        } else {

            btIngresar.setEnabled(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btIngresarKeyPressed

    private void tusuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tusuarMouseClicked
        if (evt.getButton() == 3) {
            // jPopupMenu2.show(jd_Ingresar, evt.getX(), evt.getY());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tusuarMouseClicked

    private void tusuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusuarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_tusuarActionPerformed

    private void btAgregarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAgregarArtistaActionPerformed

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIngresarActionPerformed

    private void verusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verusuarioMouseClicked
        // TODO add your handling code here:
        jd_listaaruser.pack();
        jd_listaaruser.setLocationRelativeTo(this);
        jd_listaaruser.setModal(true);
        jd_listaaruser.setVisible(true);


    }//GEN-LAST:event_verusuarioMouseClicked

    private void TablaUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaUsersMouseClicked

    private void bteliminarusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bteliminarusuarioMouseClicked
        // TODO add your handling code here:
        if (TablaUsers.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) TablaUsers.getModel();
            modelo.removeRow(TablaUsers.getSelectedRow());
            TablaUsers.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
            int selectedRow = TablaUsers.getSelectedRow();

            selectedRow = selectedRow + 1;
            usuarios.remove(selectedRow);

        }

    }//GEN-LAST:event_bteliminarusuarioMouseClicked

    private void verusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verusuarioActionPerformed
        // TODO add your handling code here:
        try {

            //limpiar tabla
            TablaUsers.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre Usuario", "Contraseña"
                    }
            ));

            // TODO add your handling code here:
            for (Usuario t : usuarios) {
                Object[] row = {t.getUsername(), t.getPassword()};
                DefaultTableModel modelo = (DefaultTableModel) TablaUsers.getModel();
                modelo.addRow(row);
                TablaUsers.setModel(modelo);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_verusuarioActionPerformed

    private void salirusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirusuarioMouseClicked
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        verusuario.setEnabled(false);
        agregarusuarioscliente.setEnabled(false);
        agregarusuariosartistas.setEnabled(false);
        eventoing.setEnabled(false);
        Gen_Simulacion.setEnabled(false);
        salirusuario.setEnabled(false);
    }//GEN-LAST:event_salirusuarioMouseClicked

    private void eventoingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventoingMouseClicked
        // TODO add your handling code here:
        jd_AgregarEvento.pack();
        jd_AgregarEvento.setLocationRelativeTo(this);
        jd_AgregarEvento.setModal(true);
        jd_AgregarEvento.setVisible(true);
    }//GEN-LAST:event_eventoingMouseClicked

    private void Gen_SimulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Gen_SimulacionMouseClicked
        // TODO add your handling code here:
         jd_Simulacion.pack();
        jd_Simulacion.setLocationRelativeTo(this);
        jd_Simulacion.setModal(true);
        jd_Simulacion.setVisible(true);
    }//GEN-LAST:event_Gen_SimulacionMouseClicked

    private void agregarusuariosclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarusuariosclienteMouseClicked
        // TODO add your handling code here:
        jd_AgregarSolista.pack();
        jd_AgregarSolista.setLocationRelativeTo(this);
        jd_AgregarSolista.setModal(true);
        jd_AgregarSolista.setVisible(true);
    }//GEN-LAST:event_agregarusuariosclienteMouseClicked

    private void agregarusuariosartistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarusuariosartistasMouseClicked
        // TODO add your handling code here:
        jd_AgregarBanda.pack();
        jd_AgregarBanda.setLocationRelativeTo(this);
        jd_AgregarBanda.setModal(true);
        jd_AgregarBanda.setVisible(true);
    }//GEN-LAST:event_agregarusuariosartistasMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
String fecha, ciudad, lugar;
int capacidad;
try {
    fecha = fecha1.getText();
    ciudad = ciudad2.getText();
    lugar = lugar2.getText();
    capacidad = Integer.parseInt(capacidad2.getText());

    Eventos s = new Eventos(fecha, ciudad, lugar, capacidad);

    String op = "s";
    int cant = 1;
    while (op.equals("s")) {
        // Mostrar la lista de canciones disponibles
        StringBuilder cancionesDisponibles = new StringBuilder("Canciones Disponibles:\n");
        for (Usuario usuario : usuarios) {
            if (usuario instanceof Bandas) {
                Bandas banda = (Bandas) usuario;
                List<Cancion> canciones = banda.getCancion();
                for (Cancion cancion : canciones) {
                    cancionesDisponibles.append("- ").append(cancion.getNombre()).append("\n");
                }
            } else if (usuario instanceof Solistas) {
                Solistas solista = (Solistas) usuario;
                List<Cancion> canciones = solista.getCancion();
                for (Cancion cancion : canciones) {
                    cancionesDisponibles.append("- ").append(cancion.getNombre()).append("\n");
                }
            }
        }
        JOptionPane.showMessageDialog(null, cancionesDisponibles.toString(), "Lista de Canciones Disponibles", JOptionPane.PLAIN_MESSAGE);

        // Resto del código para agregar canciones al evento...

        cant++;
        op = JOptionPane.showInputDialog("Desea continuar s/n");
    }

    eventos.add(s);

    adminEvento ap = new adminEvento("./Eventos.cbm");
    ap.cargarArchivo();
    ap.setEvento(s);
    ap.escribirArchivo();

    JOptionPane.showMessageDialog(this, "Valores Ingresados Correctamente");
    fecha1.setText("");
    ciudad2.setText("");
    lugar2.setText("");
    capacidad2.setText("");

    jd_AgregarEvento.setVisible(false);

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Ocurrió un error y no se guardaron los datos");
}
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    ArrayList<Usuario> usuarios = new ArrayList();
    ArrayList<Eventos> eventos = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gen_Simulacion;
    private javax.swing.JTable TablaUsers;
    private javax.swing.JButton agregarusuariosartistas;
    private javax.swing.JButton agregarusuarioscliente;
    private javax.swing.JButton btAgregarArtista;
    private javax.swing.JButton btAgregarCliente;
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton bteliminarusuario;
    private javax.swing.JTextField capacidad2;
    private javax.swing.JTextField ciudad2;
    private javax.swing.JButton eventoing;
    private javax.swing.JTextField fecha1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_AgregarBanda;
    private javax.swing.JDialog jd_AgregarEvento;
    private javax.swing.JDialog jd_AgregarSolista;
    private javax.swing.JDialog jd_Ingresar;
    private javax.swing.JDialog jd_Login;
    private javax.swing.JDialog jd_Simulacion;
    private javax.swing.JDialog jd_listaaruser;
    private javax.swing.JTextField lugar2;
    private javax.swing.JButton salirusuario;
    private javax.swing.JTextField tcont;
    private javax.swing.JTextField tcontrasena2;
    private javax.swing.JTextField tcontrasenaartista;
    private javax.swing.JTextField tedadartista;
    private javax.swing.JTextField tedadcliente;
    private javax.swing.JTextField tgenmusical1;
    private javax.swing.JTextField tgenmusical2;
    private javax.swing.JTextField tnomBanda1;
    private javax.swing.JTextField tnomartistico;
    private javax.swing.JTextField tnomuser;
    private javax.swing.JTextField tnomuser2;
    private javax.swing.JTextField tnumerointegrante1;
    private javax.swing.JTextField tusuar;
    private javax.swing.JButton verusuario;
    // End of variables declaration//GEN-END:variables
}
